#185106834 setup empty react project with vite
atlp-rwanda/destructors-ec-fe pull request #1
Opened 2023-05-05 21:47 UTC by katros1

### What does this PR do?

- This PR is for setting up a frontend react project  app

2023-05-07 12:59 UTC, buka1calvin approved these changes

2023-05-07 18:09 UTC, mjeanbosco19 commented
**@katros1** Thank you for doing this as soon as possible. I see you put up a react project using simply Vite which is good, but I don't see a CSS framework to use, like Tailwind CSS?

2023-05-07 18:10 UTC, mjeanbosco19 reviewed
@katros1 Thank you for doing this as soon as possible. I see you put up a react project using simply Vite which is good, but I don't see a CSS framework to use, like Tailwind CSS?

2023-05-07 18:15 UTC, buka1calvin commented
that's in charge of divine bro

2023-05-07 19:47 UTC, katros1 commented
> @katros1 Thank you for doing this as soon as possible. I see you put up a react project using simply Vite which is good, but I don't see a CSS framework to use, like Tailwind CSS?

yh I should have worked on that also but there are someone else who is going to take care of that.

2023-05-07 21:20 UTC, ba-lambert approved these changes
You have 2 commits

2023-05-08 04:04 UTC, leandreAlly requested changes

2023-05-08 04:04 UTC, leandreAlly commented on src/components/App.jsx
> +import { useState } from 'react'
remove app.jsx from components you're changing vite folder structure, and even app.jsx is not components

2023-05-08 04:04 UTC, leandreAlly commented on public/vite.svg
we don't need this

2023-05-08 04:04 UTC, leandreAlly commented on src/assets/react.svg
we don't need this

2023-05-08 04:38 UTC, Abdulkeza approved these changes

2023-05-08 04:39 UTC, merged