#185106855 Users view and edit profile
atlp-rwanda/destructors-ec-fe pull request #19
Opened 2023-05-15 11:34 UTC by mjeanbosco19

### What does this PR do?

- This PR is for Users should be able to view and edit their profiles
### How should this be manually tested?

**Installation**
**1. Clone the repository by running** 
```
git clone https://github.com/atlp-rwanda/destructors-ec-fe.git
```
**2. Navigate to the project directory by running**
```
cd destructors-ec-fe
```
```
git checkout ft-user-profile-185106855
```
**3. Install the necessary dependencies by running**
```
npm install
```
**4. Run react  development server by running**
```
npm run dev
```

**5. Visit in the browser below links**

### Remember that you should have a token in local storage.
```
/profile
```
```
/profile/update-profile
```
```
/profile/update-address
```

### Any background context you want to provide?
1. User Profile View on the Figma
![User Profile Figma](https://github.com/atlp-rwanda/destructors-ec-fe/assets/102979159/64c615e9-b935-4f1e-8677-ae9c05ee842d)

2. User Profile Developed
<img width="1007" alt="Screenshot 2023-05-24 at 14 37 52" src="https://github.com/atlp-rwanda/destructors-ec-fe/assets/102979159/72df54ad-4ce1-40be-bf67-e20b0d7e28d9">

3. Update Profile Account - Figma design
![Update Profile Account](https://github.com/atlp-rwanda/destructors-ec-fe/assets/102979159/7f8a715e-b2f1-44fc-a0fe-4d8ecae40198)

4. Update Profile Account - Developed Page
<img width="1235" alt="Screenshot 2023-05-24 at 14 41 15" src="https://github.com/atlp-rwanda/destructors-ec-fe/assets/102979159/dc2ce04c-fb47-4e4d-8f24-49262a57aab2">

5. Update User Billing Address  - Figma Design
![Update user billing address](https://github.com/atlp-rwanda/destructors-ec-fe/assets/102979159/d3388001-a7f8-45cb-8d04-b35c0f8f05a0)

6. Update User Address - Developed Page
<img width="1235" alt="Screenshot 2023-05-24 at 14 47 41" src="https://github.com/atlp-rwanda/destructors-ec-fe/assets/102979159/274dcc77-9dbe-4492-bdb9-256b770f5a2e">

### Questions:

- none

2023-05-26 12:53 UTC, ba-lambert requested changes
You should use react date picker for dob update
You are not catching errors

2023-05-26 12:53 UTC, ba-lambert commented on src/routes/index.jsx
> +          <Route path="/home" element={<Home />}></Route>
First of all remove these things we no longer need them

2023-05-26 13:19 UTC, buka1calvin reviewed
we can't access your endpoints it is re-redirecting us on the other page which doesn't exist

2023-05-26 13:24 UTC, katros1 commented
Im able to retrive user profile, I m only receiving `Error occurred while fetching user profile.` on the screen and i have valid token in localstorage is there something I m missing out??

2023-05-26 14:07 UTC, mjeanbosco19 commented
> we can't access your endpoints it is re-redirecting us on the other page which doesn't exist

Fixed, you can review it again

2023-05-26 14:08 UTC, mjeanbosco19 commented
> Im not able to retrieve/edit user profile, I m only receiving `Error occurred while fetching user profile.` on the screen and i have valid token in localstorage is there something else I m missing out??

Fixed, you can review it again

2023-05-26 14:09 UTC, mjeanbosco19 commented on src/routes/index.jsx
> +          <Route path="/home" element={<Home />}></Route>
Fixed, Check latest update on this PR

2023-05-26 14:18 UTC, katros1 commented
> > Im not able to retrieve/edit user profile, I m only receiving `Error occurred while fetching user profile.` on the screen and i have valid token in localstorage is there something else I m missing out??
> 
> Fixed, you can review it again

not yet Im still receiving the same error, I dont know if I m the only one

2023-05-28 16:10 UTC, ba-lambert requested changes
On my end this pr is missing too many things:
```
1.phone you must use input box not that one u uses also it must only support numbers
2.Profile fetching is not working as it should in redux there is data but are not being displaied in the forms 
3. the user interface is not matching with what is on the figma
4. Dob must be a date picker not input also must catch current date so that you are not born in future
5. lastly you are not catching messages from the backend either success or error message here you should use tostify
```

Also in the code you are writing a big component file it would be better if you try to use those ones which are reusable

much respect on your tests

![Screenshot (118)](https://github.com/atlp-rwanda/destructors-ec-fe/assets/50544115/f365f0a6-b050-43df-9bcf-7264b9970769)

2023-05-29 08:18 UTC, mjeanbosco19 commented
> On my end this pr is missing too many things:
> 
> ```
> 1.phone you must use input box not that one u uses also it must only support numbers
> 2.Profile fetching is not working as it should in redux there is data but are not being displaied in the forms 
> 3. the user interface is not matching with what is on the figma
> 4. Dob must be a date picker not input also must catch current date so that you are not born in future
> 5. lastly you are not catching messages from the backend either success or error message here you should use tostify
> ```
> 
> Also in the code you are writing a big component file it would be better if you try to use those ones which are reusable
> 
> much respect on your tests
> 
> ![Screenshot (118)](https://user-images.githubusercontent.com/50544115/241572362-f365f0a6-b050-43df-9bcf-7264b9970769.png)

Thanks @ba-lambert for your details review. I worked on all of those feedback. However I can't see any issue related to data fetching according to screenshot you provided. I would like to request to review it again, and let me know I you still have any concern. Thanks

2023-05-29 13:28 UTC, leandreAlly requested changes

2023-05-29 13:28 UTC, leandreAlly commented on src/components/profile/EditAddress.jsx
> +
This is too much, use react-hook-form instead of creating state for every input fields

2023-05-29 13:28 UTC, leandreAlly commented on src/components/profile/EditAddress.jsx
> +
This is too much , you need to use react-hook-form for handling the you form functionalities instead of creating state for every task

2023-05-29 13:28 UTC, leandreAlly commented on src/components/profile/EditAddress.jsx
> +  }
use spinner which has created by @ba-lambert

2023-05-29 13:28 UTC, leandreAlly commented on src/components/profile/EditProfile.jsx
> +
remove this state and use react-hook-form

2023-05-30 13:13 UTC, leandreAlly approved these changes
please

2023-05-30 13:20 UTC, katros1 approved these changes

2023-05-30 14:49 UTC, buka1calvin approved these changes

2023-05-31 15:37 UTC, merged