feature(ft-google-login-185106846):add user login via google
atlp-rwanda/destructors-ec-fe pull request #20
Opened 2023-05-15 11:40 UTC by divinecharlotte

2023-05-17 11:51 UTC, denislohan requested changes
1. PR named Wrong

2023-05-17 13:17 UTC, leandreAlly requested changes

2023-05-17 13:17 UTC, leandreAlly commented on src/components/GoggleLogin.jsx
> +  };
use environment variables instead of hard coding values

2023-05-18 09:45 UTC, divinecharlotte commented
> 1. PR named Wrong
hello @denislohan 
 

- [x] renamed well

2023-05-22 08:49 UTC, ba-lambert commented
@divinecharlotte how this pr is tested cz this endpoint you gave us contains nothing

2023-05-22 10:12 UTC, ba-lambert reviewed
how this pr is tested cz this endpoint you gave us contains nothing

2023-05-22 10:51 UTC, divinecharlotte commented
> how this pr is tested cz this endpoint you gave us contains nothing

@ba-lambert  check pr description updated

2023-05-22 12:11 UTC, ba-lambert approved these changes

2023-05-22 13:00 UTC, JENNY-257 approved these changes

2023-05-22 13:07 UTC, katros1 approved these changes

2023-05-22 16:45 UTC, merged