Ft admin disable account 185106857
atlp-rwanda/destructors-ec-fe pull request #21
Opened 2023-05-15 13:49 UTC by nkurunziza1

2023-05-28 15:26 UTC, JENNY-257 approved these changes

2023-05-28 16:41 UTC, ba-lambert approved these changes
Perfect user interface
but the list should be not touching on the bottom
font should be poppins
1 test failing

2023-05-29 10:47 UTC, mjeanbosco19 approved these changes

2023-05-29 11:05 UTC, katros1 requested changes

2023-05-29 11:05 UTC, katros1 commented on tailwind.config.js
>        fontFamily: {
why did you remove  these  colors ??

2023-05-29 11:05 UTC, katros1 commented on tailwind.config.js
> -      laptop: { max: "1165px"}
why did you remove these tailwind screen configuration, some of us used them in responsiveness

2023-05-29 11:50 UTC, katros1 commented
also your mobile version don,t meet what we have on our figma, try to remove the status button  on mobile devices. use ellipsis dots instead as what is in figma

2023-05-30 08:00 UTC, leandreAlly commented on src/components/Admin/Users.jsx
> +
clean this if you don't need them

2023-05-30 08:07 UTC, leandreAlly approved these changes

2023-05-30 08:22 UTC, merged