chore(Setup Tailwind CSS):Setup Tailwind CSS processing on the client
atlp-rwanda/destructors-ec-fe pull request #3
Opened 2023-05-08 13:21 UTC by divinecharlotte

### What does this PR do?

- This PR is for Setting up Tailwind CSS processing on the client

### How should this be manually tested?

**Installation**
**1. Clone the repository by running** 
```
git clone https://github.com/atlp-rwanda/destructors-ec-fe.git
```
**2. Navigate to the project directory by running **
```
cd destructors-ec-fe
```
```
git checkout ch-setup-tailwindCss-185106839
```
**3. Install the necessary dependencies by running **
```
npm install
```
**6. Run react  development server by running**
```
npm run dev
```

### Any background context you want to provide?
N/A

### Questions:

- none

2023-05-08 13:49 UTC, ba-lambert approved these changes

2023-05-09 06:33 UTC, katros1 approved these changes

2023-05-09 08:49 UTC, leandreAlly requested changes

2023-05-09 08:49 UTC, leandreAlly commented on src/components/header.jsx
> +import React from 'react'
every components must start with capital letter as naming conventions.

2023-05-09 08:49 UTC, leandreAlly commented on src/App.jsx
>  import { useState } from 'react'
can you create your components for testing styling purpose not adding your styles into the App.jsx

2023-05-09 13:12 UTC, buka1calvin approved these changes

2023-05-09 16:29 UTC, leandreAlly approved these changes

2023-05-09 16:39 UTC, JENNY-257 approved these changes

2023-05-09 17:45 UTC, mjeanbosco19 approved these changes

2023-05-09 18:01 UTC, Abdulkeza approved these changes
Nice work

2023-05-09 18:02 UTC, Abdulkeza reviewed
Nice work, but you need to solve conflicts

2023-05-10 11:28 UTC, merged