add post product to wishlist
atlp-rwanda/destructors-ec-fe pull request #37
Opened 2023-06-06 10:21 UTC by divinecharlotte

2023-06-10 11:50 UTC, ba-lambert requested changes
**No PR description is around**
```
Why you are violating eslint rules cz it will be harder and harder for us to commit when we rebase your changes
```
> Hover should not change the design of a product card at landing page
what expected: 
![Screenshot 2023-06-10 132701](https://github.com/atlp-rwanda/destructors-ec-fe/assets/50544115/be34d74f-dfaa-4710-bfcf-08373d80ace7)


> How a user will be navigated to wishlist page?? (sugention: add an icon on nav bar for wish lised products navigation)

> How a user should remove a wished product to wishlist page?? (sugetion:  add an icon to unwish product also should be visible when we hover a product)
what you have
![Screenshot 2023-06-10 133000](https://github.com/atlp-rwanda/destructors-ec-fe/assets/50544115/3fe8dab2-8b08-45e5-9bc7-7014f6095fe3)
how you should do it 
![Screenshot 2023-06-10 133801](https://github.com/atlp-rwanda/destructors-ec-fe/assets/50544115/fb2bfc5e-59d1-45f8-bd9f-4419983d1ace)
> Single product add to cart is not working you have to work on its functionality and change bg when product is already wished

💪 Happy coding

2023-06-12 06:12 UTC, Abdulkeza requested changes
Try to clean your code Divine

2023-06-12 06:12 UTC, Abdulkeza commented on src/components/products/Product.jsx
> +// export default Product;
Please could you remove this, we don't really need it

2023-06-12 06:28 UTC, buka1calvin approved these changes

2023-06-12 07:19 UTC, mjeanbosco19 requested changes
Good morning @divinecharlotte , Great Job! I one changes I request on your PR is to automatically increment or decrement number of wished products on the Wishes Icon. As you can see the number on the Icon does dynamically updated.

2023-06-12 08:35 UTC, ba-lambert approved these changes

2023-06-12 09:34 UTC, mjeanbosco19 approved these changes

2023-06-12 10:46 UTC, Abdulkeza approved these changes

2023-06-12 10:46 UTC, merged