Ft logout 185335669
atlp-rwanda/destructors-ec-fe pull request #39
Opened 2023-06-06 11:46 UTC by nkurunziza1

2023-06-09 14:22 UTC, katros1 requested changes

2023-06-09 14:22 UTC, katros1 commented on src/components/SideBar.jsx
>      if (location) {
add this logout functionality on navbar for dashboard, because this sidebar will be removed

2023-06-12 14:18 UTC, mjeanbosco19 approved these changes

2023-06-12 14:23 UTC, katros1 approved these changes

2023-06-12 14:26 UTC, JENNY-257 approved these changes

2023-06-12 14:27 UTC, merged