chore(add-eslint-houndCi-184859055): add config eslint and houndCI wi…
atlp-rwanda/destructors-ec-fe pull request #4
Opened 2023-05-08 14:24 UTC by nkurunziza1

2023-05-09 08:01 UTC, mjeanbosco19 reviewed
@nkurunziza1 It works but babel-eslint is now @babel/eslint-parser. This package will no longer receive updates. Should you use @babel/eslint-parser?

2023-05-09 08:49 UTC, divinecharlotte requested changes

2023-05-09 08:49 UTC, divinecharlotte commented on package.json
> +    "precommit": "lint-staged",
- [ ] kindly consider adding the command to run the pre-commit in your pr description cause its just there but has no command consider the person reviewing it doesn't know to check in the package.json

2023-05-09 09:05 UTC, leandreAlly commented on .babelrc
> +{
can you help me to understand why do we need babel, I thought vite can handle all the tasks for us?

2023-05-15 09:04 UTC, buka1calvin approved these changes

2023-05-15 18:00 UTC, katros1 reviewed
the husky pre commit are are being ignored, is there anything I can do  to make them run or you didn't notice it while you well testing on you laptop

2023-05-16 20:57 UTC, katros1 approved these changes

2023-05-17 04:53 UTC, ba-lambert approved these changes

2023-05-17 04:54 UTC, ba-lambert commented
It would be better if you squash your 6 commits into 1

2023-05-17 08:07 UTC, mjeanbosco19 approved these changes

2023-05-18 09:06 UTC, merged