#185106860 feature(chat-app):users should be able to chat
atlp-rwanda/destructors-ec-fe pull request #42
Opened 2023-06-06 17:35 UTC by buka1calvin

2023-06-11 16:04 UTC, katros1 requested changes
you did a great job @buka1calvin  👍 , 
but you need to make some few changes:

1.  when u refresh the user must get all messages which were sent before.
2. use local time of the user 
3.  try to work on the name of the user some are not being displayed
4.   try to increase the message block on desktop view
5. reduce the roundness of the corner of the message block they are to big
6.  refer to this :👇🏾
<img width="664" alt="Screen Shot 2023-06-11 at 17 59 46" src="https://github.com/atlp-rwanda/destructors-ec-fe/assets/101397608/4d24579d-61b3-4beb-8ff7-170308cc2ff0">

2023-06-11 18:21 UTC, nkurunziza1 approved these changes

2023-06-11 22:22 UTC, katros1 approved these changes

2023-06-11 22:22 UTC, katros1 commented on src/components/products/Product.jsx
> +  // console.log("User ID:", userId);
remember to remove these console.log and unnecessary comments

2023-06-12 06:50 UTC, divinecharlotte approved these changes

2023-06-12 07:46 UTC, ba-lambert requested changes
You are displaying only senders messages when you reflesh the page

2023-06-12 08:16 UTC, merged