fix cart and wishlist count
atlp-rwanda/destructors-ec-fe pull request #46
Opened 2023-06-15 17:30 UTC by divinecharlotte

2023-06-17 15:26 UTC, ba-lambert requested changes
How a buyer will know that the product is already wished??

> Also the design on the cart is totally different from what is on the figma
![Screenshot 2023-06-17 194644](https://github.com/atlp-rwanda/destructors-ec-fe/assets/50544115/b5a747ac-7512-4dd0-a481-0a0d8d99ed43)
![Screenshot 2023-06-17 194725](https://github.com/atlp-rwanda/destructors-ec-fe/assets/50544115/949734da-114c-46a8-91cd-050c44ff9b61)

2023-06-18 21:10 UTC, ba-lambert reviewed
How a buyer will know that the product is already wished??

> Also the design on the cart is totally different from what is on the figma
![Screenshot 2023-06-17 194644](https://github.com/atlp-rwanda/destructors-ec-fe/assets/50544115/b5a747ac-7512-4dd0-a481-0a0d8d99ed43)
![Screenshot 2023-06-17 194725](https://github.com/atlp-rwanda/destructors-ec-fe/assets/50544115/949734da-114c-46a8-91cd-050c44ff9b61)

2023-06-19 12:26 UTC, JENNY-257 approved these changes

2023-06-19 12:43 UTC, nkurunziza1 approved these changes

2023-06-19 12:46 UTC, mjeanbosco19 approved these changes

2023-06-19 13:34 UTC, buka1calvin approved these changes

2023-06-19 14:26 UTC, merged