#185106844 chore storybook installation and configuration
atlp-rwanda/destructors-ec-fe pull request #9
Opened 2023-05-08 19:44 UTC by buka1calvin

2023-05-11 15:32 UTC, mjeanbosco19 requested changes
@buka1calvin You should solve this error in your codes shown when I run this command to test storybook.
<img width="1426" alt="Screenshot 2023-05-11 at 18 29 42" src="https://github.com/atlp-rwanda/destructors-ec-fe/assets/102979159/2f28b204-389f-4831-9f00-d60e2670b98c">

2023-05-14 13:57 UTC, nkurunziza1 approved these changes

2023-05-15 07:24 UTC, katros1 approved these changes

2023-05-15 09:23 UTC, mjeanbosco19 approved these changes

2023-05-15 09:52 UTC, merged